require("dotenv").config();
require("module-alias-jest/register");
const { app } = require("@root/src/app");
const request = require("supertest");
const jwt = require("jsonwebtoken");
const jwt_secret = process.env["JWT_SECRET"];

const { exportForTestingOnly: testExp, authorization } = require("@middlewares/authorization");

describe("generateAccessToken tests", () => {
	beforeEach(function () {
		// Stub the clock with sinon;
		jest.useFakeTimers();
	});

	afterEach(function () {
		// Restore current clock for other tests
		jest.useRealTimers();
	});

	test("token generated by generateAccessToken succeeds to verify when token not expired", (done) => {
		const token = jwt.sign({ username: "atahan1006" }, jwt_secret, { expiresIn: 60 });

		jest.advanceTimersByTime(5000);

		jwt.verify(token, jwt_secret, function (err) {
			expect(err).toBeNull();
			done();
		});
	});

	test("token generated by generateAccessToken fails to verify when token expires.", (done) => {
		const token = jwt.sign({ username: "atahan1006" }, jwt_secret, { expiresIn: 60 });

		jest.advanceTimersByTime(62000);

		jwt.verify(token, jwt_secret, function (err) {
			expect(err).not.toBeNull();
			done();
		});
	});
});

describe("authorization middleware tests", () => {
	const { connection: mysql_connection } = require("@utils/database-connection");

	afterAll(() => {
		mysql_connection.end();
	});

	beforeEach(() => {
		jest.useFakeTimers();
	});

	afterEach(() => {
		jest.useRealTimers();
	});

	app.get("/", authorization, function (req, res) {
		res.status(200).json({ message: "everything is ok" });
	});

	it("forwards to next endpoint if access_token is valid", () => {
		expect.assertions(1);

		const token = testExp.generateAccessToken("atahan1006", 60);

		return request(app)
			.get("/")
			.send({ access_token: token })
			.then((response) => {
				expect(response.statusCode).toBe(200);
			});
	});

	it("forwards to next endpoint if request_token is valid", (done) => {
		expect.assertions(1);
		let access_token = testExp.generateAccessToken("atahan1006", 60);

		mysql_connection.query(`SELECT * FROM authentication_token LIMIT 1`, function (err, results) {
			if (Boolean(err) !== false) {
				console.error(err);
				done(err);
				return;
			}

			if (results.length === 0) {
				done("no token in database to be used.");
				return;
			}

			// expire the access token on purpose by moving time more than 60 seconds

			jest.advanceTimersByTime(62000);

			let refresh_token = results[0].token;

			request(app)
				.get("/")
				.send({ access_token, refresh_token })
				.then((response) => {
					expect(response.statusCode).toBe(200);
					done();
				})
				.catch((error) => {
					done(error);
					return;
				});
		});
	});

	it("rejects call next when refresh token is not valid", (done) => {
		let refresh_token = "litterally invalid";
		request(app)
			.get("/")
			.send({ refresh_token })
			.then((response) => {
				expect(response.statusCode).toBe(401);
				done();
			})
			.catch((error) => {
				done(error);
				return;
			});
	});
});
