require("@shared/config").config();
require("module-alias-jest/register");
const request = require("supertest");
const jwt = require("jsonwebtoken");
const jwt_secret = process.env["JWT_SECRET"];
const { app } = require("@root/src/app");
const { exportForTestingOnly: testExp, authorization } = require("@middlewares/authorization");
const { connection: mysql_connection } = require("@shared/database-connection");

beforeAll(() => {});
afterAll(() => {
	mysql_connection.end();
});

describe("helper functions tests", () => {
	beforeEach(function () {
		// Stub the clock with sinon;
		jest.useFakeTimers();
	});

	afterEach(function () {
		// Restore current clock for other tests
		jest.useRealTimers();
	});

	test("token generated by generateAccessToken succeeds to verify when token not expired", (done) => {
		const token = jwt.sign({ username: "atahan1006" }, jwt_secret, { expiresIn: 60 });

		jest.advanceTimersByTime(5000);

		jwt.verify(token, jwt_secret, function (err) {
			expect(err).toBeNull();
			done();
		});
	});

	test("token generated by generateAccessToken fails to verify when token expires.", (done) => {
		const token = jwt.sign({ username: "atahan1006" }, jwt_secret, { expiresIn: 60 });

		jest.advanceTimersByTime(62000);

		jwt.verify(token, jwt_secret, function (err) {
			try {
				expect(err).not.toBeNull();
				done();
			} catch (err) {
				done(err);
			}
		});
	});
});
